In [ ]:
!pip install numpy
!pip install pandas
!pip install IPython

In [1]:
import pandas as pd
import numpy as np

In [13]:
poverty = pd.read_csv('resources/poverty.csv')
wdi = pd.read_csv('resources/WDI.csv', delimiter=';')
education = pd.read_csv('resources/Data_Extract_From_Education_Statistics_-_All_Indicators.csv')
label = pd.read_csv('resources/label-set.csv')

education = education.replace({'..':np.nan})
wdi = wdi.replace({'..':np.nan})
poverty = poverty.replace({'..':np.nan})
label = label.replace({'..':np.nan})

In [14]:
df = reduce(lambda left,right: pd.merge(left,right,on=['Time', 'Country Name']), [education, wdi, label])

In [15]:
df = df.loc[df['CO2 emissions (metric tons per capita) [EN.ATM.CO2E.PC]'] != 'NaN']

In [16]:
df = df.rename(columns={"Time Code_x": "Time Code", "Country Name_x": "Country Name"})
del df['Time Code_y']
del df['Country Code_x']

In [17]:
df

,Time,Time Code,Country Name,"Percentage of graduates from tertiary education graduating from Agriculture, Forestry, Fisheries and Veterinary programmes, both sexes (%) [SE.TER.GRAD.AG.ZS]",Government expenditure on education as % of GDP (%) [SE.XPD.TOTL.GD.ZS],"Enrolment in tertiary education, all programmes, both sexes (number) [SE.TER.ENRL]","Percentage of graduates from tertiary education graduating from Natural Sciences, Mathematics and Statistics programmes, both sexes (%) [SE.TER.GRAD.SC.ZS]","Enrolment in primary education, both sexes (number) [SE.PRM.ENRL]",Energy use (kg of oil equivalent per capita),GDP per capita growth (annual %),...,"Manufacturing, value added (annual % growth)",Urban population (% of total population),Merchandise imports (current US$),Merchandise exports (current US$),Population growth (annual %),Final consumption expenditure (annual % growth),Alternative and nuclear energy (% of total energy use),Fossil fuel energy consumption (% of total),Country Code_y,CO2 emissions (metric tons per capita) [EN.ATM.CO2E.PC]
0,2016,YR2016,Afghanistan,NaN,4.22836,NaN,NaN,6265011,NaN,"-0,541697283",...,"1,087939531","25,02",6534000000,596000000,"2,778317409",NaN,NaN,NaN,AFG,0.245101422
1,2016,YR2016,Albania,4.12656,3.96209,148597,4.66126,179564,NaN,"3,480117005",...,"4,541159357","58,421",4613000000,1959000000,"-0,159880412","2,437851728",NaN,NaN,ALB,1.577162624
2,2016,YR2016,Algeria,1.35872,NaN,1439594,11.84467,4118362,NaN,"1,104567921",...,"6,028074388","71,459",47089000000,30026000000,"2,051354584","2,6",NaN,NaN,DZA,3.69915599
3,2016,YR2016,American Samoa,NaN,NaN,NaN,NaN,NaN,NaN,"-2,645383249",...,NaN,"87,198",655000000,388000000,"-0,12729377",NaN,NaN,NaN,ASM,NaN
4,2016,YR2016,Andorra,0,3.23707,548,0,4248,NaN,"4,667654578",...,NaN,"88,248",1354000000,97000000,"-0,919469738",NaN,NaN,NaN,AND,6.072370208
5,2016,YR2016,Angola,NaN,NaN,253287,NaN,NaN,NaN,"-5,81623672",...,"11,63811067","64,149",13040000000,27589000000,"3,37827278","1,842463673",NaN,NaN,AGO,1.202860579
6,2016,YR2016,Antigua and Barbuda,NaN,NaN,NaN,NaN,NaN,NaN,"4,42525495",...,"6,400651466","24,846",478000000,61000000,"1,021843835",NaN,NaN,NaN,ATG,5.896558655
7,2016,YR2016,Arab World,NaN,NaN,10951281.7,NaN,46378905.57,NaN,"1,374916531",...,"3,672195528","58,34527548","7,86094E+11","7,93613E+11","2,019087384","-0,479230948",NaN,NaN,ARB,4.712844702
8,2016,YR2016,Argentina,NaN,5.54549,3061139,NaN,4775782,NaN,"-3,110063898",...,"-5,601139739","91,627",55852000000,57910000000,"1,057181578","-0,740187841",NaN,NaN,ARG,4.619085482
9,2016,YR2016,Armenia,5.17879,2.75812,109330,5.25495,148481,NaN,"-0,16150062",...,"11,1","63,082",3273000000,1792000000,"0,361431439","-1,206822509",NaN,NaN,ARM,1.755976031
10,2016,YR2016,Aruba,0,5.52415,1191,2.22222,NaN,NaN,"1,583035098",...,NaN,"43,192",1208147000,300000000,"0,50761773",NaN,NaN,NaN,ABW,8.426910901
11,2016,YR2016,Australia,NaN,5.27678,1918625,NaN,2179689,NaN,"1,177911433",...,"-2,439250345","85,8","1,9627E+11","1,92505E+11","1,561940498","3,11098891",NaN,NaN,AUS,15.53922046
12,2016,YR2016,Austria,1.64679,5.48435,431124.9548,5.75421,329031.5,NaN,"0,984638283",...,"4,558755808","57,905","1,57697E+11","1,5209E+11","1,081396299","1,666647955",NaN,NaN,AUT,7.033335706
13,2016,YR2016,Azerbaijan,1.18231,2.90341,207604,3.9462,580980,NaN,"-4,141174903",...,"-1,19655259","55,021",8489000000,13108000000,"1,11785721",NaN,NaN,NaN,AZE,3.855347182
14,2016,YR2016,"Bahamas, The",NaN,NaN,NaN,NaN,30655,NaN,"-0,543773106",...,"39,00654601","82,832",2632000000,481000000,"0,990519136","-1,321434189",NaN,NaN,BHS,4.725277895
15,2016,YR2016,Bahrain,0,NaN,40669,1.71111,112179,NaN,"-0,441055395",...,"5,21120944","89,09",9170000000,12785000000,"3,856582461","-0,4970447",NaN,NaN,BHR,22.22898097
16,2016,YR2016,Bangladesh,1.12429,1.53554,2699345,7.9521,NaN,NaN,"5,950927422",...,"11,6908152","35,083",44772000000,34894000000,"1,091300482","3,399133115",NaN,NaN,BGD,0.533298791
17,2016,YR2016,Barbados,NaN,4.95139,NaN,NaN,20731,NaN,"2,309452277",...,"-1,259349517","31,193",1622000000,517000000,"0,165289294",NaN,NaN,NaN,BRB,4.465128973
18,2016,YR2016,Belarus,4.34431,4.94655,443997,2.70928,410487,NaN,"-2,648709831",...,"-0,050959742","77,661",27610000000,23537000000,"0,12551111","-2,45222563",NaN,NaN,BLR,6.133707568
19,2016,YR2016,Belgium,1.95483,6.45954,508270,3.92056,797390,NaN,"0,965814583",...,"-1,780565781","97,919","3,79409E+11","3,98134E+11","0,506300002","1,439962604",NaN,NaN,BEL,8.550513254
20,2016,YR2016,Belize,NaN,7.28477,9097,NaN,52333,NaN,"-1,943516255",...,"-7,538252382","45,495",953000000,443000000,"2,047695884","5,857499113",NaN,NaN,BLZ,1.542847448
21,2016,YR2016,Benin,NaN,2.8991,129302,NaN,2267835,NaN,"0,525081923",...,"6,43171428","46,229",2872000000,1774000000,"2,761409493","0,854737509",NaN,NaN,BEN,0.595647727
22,2016,YR2016,Bermuda,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,100,977000000,19000000,"-1,046951883",NaN,NaN,NaN,BMU,9.486460947
23,2016,YR2016,Bhutan,NaN,6.99333,NaN,NaN,96654,NaN,"6,830611088",...,"2,423097295","39,428",1002000000,525000000,"1,206226624","-2,932239127",NaN,NaN,BTN,1.712274453
24,2016,YR2016,Bolivia,NaN,NaN,NaN,NaN,1354038,NaN,"2,732042257",...,"6,184823211","68,738",8427000000,7082000000,"1,480132784","3,130600412",NaN,NaN,BOL,1.958514344
25,2016,YR2016,Bosnia and Herzegovina,4.33777,NaN,106975,7.30334,161560,NaN,"4,458295013",...,"5,386810716","47,518",9146000000,5328000000,"-1,264581174","1,794706821",NaN,NaN,BIH,6.451938373
26,2016,YR2016,Botswana,NaN,NaN,51573,NaN,NaN,NaN,"2,40941658",...,"1,550495551","67,933",6143000000,7366000000,"1,832852792","2,257485627",NaN,NaN,BWA,2.935373787
27,2016,YR2016,Brazil,2.57929,6.31404,8319089,2.67247,16118565,NaN,"-4,069407164",...,"-4,768195697","86,042","1,43411E+11","1,85232E+11","0,823748232","-2,939141146",NaN,NaN,BRA,2.242393446
28,2016,YR2016,British Virgin Islands,NaN,NaN,834,NaN,3309,NaN,NaN,...,NaN,"46,957",NaN,NaN,"0,693936844",NaN,NaN,NaN,VGB,7.245307443
29,2016,YR2016,Brunei Darussalam,0,4.42541,11010,NaN,40471,NaN,"-3,614591507",...,"-0,713529367","76,99",2679000000,4875000000,"1,172400865","-4,239363517",NaN,NaN,BRN,18.25638399
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12358,1970,YR1970,"Yemen, Rep.",NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,"13,3",33000000,3000000,"1,567903809",NaN,NaN,NaN,YEM,0.027235837
12359,1970,YR1970,Zambia,NaN,4.38781,1433,NaN,694670,NaN,"1,453714802",...,"8,030927439","30,351",477000000,1001000000,"3,24235402",NaN,NaN,NaN,ZMB,0.902037704
12360,1970,YR1970,Zimbabwe,NaN,NaN,NaN,NaN,735782,NaN,"18,44127485",...,"11,76516272","17,362",378000000,370000000,"3,422546533",NaN,NaN,NaN,ZWE,1.543254754
12361,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12362,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12363,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12364,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12365,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12366,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12367,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12368,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12369,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12370,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12371,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12372,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12373,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12374,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12375,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12376,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12377,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12378,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12379,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12380,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12381,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12382,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12383,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12384,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12385,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12386,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12387,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [18]:
df.to_csv('andmed.csv', index=False) #Create a csv from the data

IOError: [Errno 13] Permission denied: 'andmed.csv'

,Time,Time Code_x,Country Name_x,Country Code,"Percentage of graduates from tertiary education graduating from Agriculture, Forestry, Fisheries and Veterinary programmes, both sexes (%) [SE.TER.GRAD.AG.ZS]",Government expenditure on education as % of GDP (%) [SE.XPD.TOTL.GD.ZS],"Enrolment in tertiary education, all programmes, both sexes (number) [SE.TER.ENRL]","Percentage of graduates from tertiary education graduating from Natural Sciences, Mathematics and Statistics programmes, both sexes (%) [SE.TER.GRAD.SC.ZS]","Enrolment in primary education, both sexes (number) [SE.PRM.ENRL]",Time Code_y,Country Name_y,CO2 emissions (metric tons per capita) [EN.ATM.CO2E.PC]
0,2020,YR2020,Afghanistan,AFG,NaN,NaN,NaN,NaN,NaN,YR2020,Afghanistan,NaN
1,2020,YR2020,Albania,ALB,NaN,NaN,NaN,NaN,NaN,YR2020,Albania,NaN
2,2020,YR2020,Algeria,DZA,NaN,NaN,NaN,NaN,NaN,YR2020,Algeria,NaN
3,2020,YR2020,American Samoa,ASM,NaN,NaN,NaN,NaN,NaN,YR2020,American Samoa,NaN
4,2020,YR2020,Andorra,AND,NaN,NaN,NaN,NaN,NaN,YR2020,Andorra,NaN
5,2020,YR2020,Angola,AGO,NaN,NaN,NaN,NaN,NaN,YR2020,Angola,NaN
6,2020,YR2020,Antigua and Barbuda,ATG,NaN,NaN,NaN,NaN,NaN,YR2020,Antigua and Barbuda,NaN
7,2020,YR2020,Arab World,ARB,NaN,NaN,NaN,NaN,NaN,YR2020,Arab World,NaN
8,2020,YR2020,Argentina,ARG,NaN,NaN,NaN,NaN,NaN,YR2020,Argentina,NaN
9,2020,YR2020,Armenia,ARM,NaN,NaN,NaN,NaN,NaN,YR2020,Armenia,NaN
10,2020,YR2020,Aruba,ABW,NaN,NaN,NaN,NaN,NaN,YR2020,Aruba,NaN
11,2020,YR2020,Australia,AUS,NaN,NaN,NaN,NaN,NaN,YR2020,Australia,NaN
12,2020,YR2020,Austria,AUT,NaN,NaN,NaN,NaN,NaN,YR2020,Austria,NaN
13,2020,YR2020,Azerbaijan,AZE,NaN,NaN,NaN,NaN,NaN,YR2020,Azerbaijan,NaN
14,2020,YR2020,"Bahamas, The",BHS,NaN,NaN,NaN,NaN,NaN,YR2020,"Bahamas, The",NaN
15,2020,YR2020,Bahrain,BHR,NaN,NaN,NaN,NaN,NaN,YR2020,Bahrain,NaN
16,2020,YR2020,Bangladesh,BGD,NaN,NaN,NaN,NaN,NaN,YR2020,Bangladesh,NaN
17,2020,YR2020,Barbados,BRB,NaN,NaN,NaN,NaN,NaN,YR2020,Barbados,NaN
18,2020,YR2020,Belarus,BLR,NaN,NaN,NaN,NaN,NaN,YR2020,Belarus,NaN
19,2020,YR2020,Belgium,BEL,NaN,NaN,NaN,NaN,NaN,YR2020,Belgium,NaN
20,2020,YR2020,Belize,BLZ,NaN,NaN,NaN,NaN,NaN,YR2020,Belize,NaN
21,2020,YR2020,Benin,BEN,NaN,NaN,NaN,NaN,NaN,YR2020,Benin,NaN
22,2020,YR2020,Bermuda,BMU,NaN,NaN,NaN,NaN,NaN,YR2020,Bermuda,NaN
23,2020,YR2020,Bhutan,BTN,NaN,NaN,12248,NaN,94165,YR2020,Bhutan,NaN
24,2020,YR2020,Bolivia,BOL,NaN,NaN,NaN,NaN,NaN,YR2020,Bolivia,NaN
25,2020,YR2020,Bosnia and Herzegovina,BIH,NaN,NaN,NaN,NaN,NaN,YR2020,Bosnia and Herzegovina,NaN
26,2020,YR2020,Botswana,BWA,NaN,NaN,NaN,NaN,NaN,YR2020,Botswana,NaN
27,2020,YR2020,Brazil,BRA,NaN,NaN,NaN,NaN,NaN,YR2020,Brazil,NaN
28,2020,YR2020,British Virgin Islands,VGB,NaN,NaN,NaN,NaN,NaN,YR2020,British Virgin Islands,NaN
29,2020,YR2020,Brunei Darussalam,BRN,NaN,NaN,NaN,NaN,NaN,YR2020,Brunei Darussalam,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
13392,1970,YR1970,Turkey,TUR,NaN,NaN,NaN,NaN,NaN,YR1970,Turkey,1.222603095
13393,1970,YR1970,Turkmenistan,TKM,NaN,NaN,NaN,NaN,NaN,YR1970,Turkmenistan,NaN
13394,1970,YR1970,Turks and Caicos Islands,TCA,NaN,NaN,NaN,NaN,NaN,YR1970,Turks and Caicos Islands,NaN
13395,1970,YR1970,Tuvalu,TUV,NaN,NaN,NaN,NaN,NaN,YR1970,Tuvalu,NaN
13396,1970,YR1970,Uganda,UGA,NaN,NaN,4232,NaN,729522,YR1970,Uganda,0.153610402
13397,1970,YR1970,Ukraine,UKR,NaN,4.57293,NaN,NaN,NaN,YR1970,Ukraine,NaN
13398,1970,YR1970,United Arab Emirates,ARE,NaN,NaN,NaN,NaN,NaN,YR1970,United Arab Emirates,65.01695421
13399,1970,YR1970,United Kingdom,GBR,NaN,NaN,NaN,NaN,NaN,YR1970,United Kingdom,11.7323973
13400,1970,YR1970,United States,USA,NaN,NaN,NaN,NaN,NaN,YR1970,United States,21.11125227
13401,1970,YR1970,Upper middle income,UMC,NaN,NaN,8891124.611,NaN,188462276.9,YR1970,Upper middle income,2.862150253
13402,1970,YR1970,Uruguay,URY,NaN,NaN,NaN,NaN,354096,YR1970,Uruguay,2.043752689
13403,1970,YR1970,Uzbekistan,UZB,NaN,NaN,NaN,NaN,NaN,YR1970,Uzbekistan,NaN
13404,1970,YR1970,Vanuatu,VUT,NaN,NaN,NaN,NaN,18250,YR1970,Vanuatu,0.472457453
13405,1970,YR1970,"Venezuela, RB",VEN,NaN,4.16287,NaN,NaN,NaN,YR1970,"Venezuela, RB",6.542518409
13406,1970,YR1970,Vietnam,VNM,NaN,NaN,NaN,NaN,NaN,YR1970,Vietnam,0.649680094
13407,1970,YR1970,Virgin Islands (U.S.),VIR,NaN,NaN,NaN,NaN,NaN,YR1970,Virgin Islands (U.S.),NaN
13408,1970,YR1970,West Bank and Gaza,PSE,NaN,NaN,NaN,NaN,NaN,YR1970,West Bank and Gaza,NaN
13409,1970,YR1970,World,WLD,NaN,NaN,31977939.65,NaN,401201714.7,YR1970,World,0.00403549
13410,1970,YR1970,"Yemen, Rep.",YEM,NaN,NaN,NaN,NaN,NaN,YR1970,"Yemen, Rep.",0.027235837
13411,1970,YR1970,Zambia,ZMB,NaN,4.38781,1433,NaN,694670,YR1970,Zambia,0.902037704
13412,1970,YR1970,Zimbabwe,ZWE,NaN,NaN,NaN,NaN,735782,YR1970,Zimbabwe,1.543254754
13413,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13414,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13415,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13416,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13417,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13418,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13419,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13420,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13421,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN