In [ ]:
!pip install numpy
!pip install pandas
!pip install IPython

In [2]:
import pandas as pd
import numpy as np

In [10]:
poverty = pd.read_csv('resources/poverty.csv')
wdi = pd.read_csv('resources/WDI.csv')
education = pd.read_csv('resources/Data_Extract_From_Education_Statistics_-_All_Indicators.csv')
label = pd.read_csv('resources/label-set.csv')

education = education.replace({'..':np.nan})
wdi = wdi.replace({'..':np.nan})
poverty = poverty.replace({'..':np.nan})
label = label.replace({'..':np.nan})

ParserError: Error tokenizing data. C error: Expected 3 fields in line 12, saw 6

In [15]:
df = reduce(lambda left,right: pd.merge(left,right,on=['Time', 'Country Code']), [education, label])

In [19]:
df = df.loc[df['CO2 emissions (metric tons per capita) [EN.ATM.CO2E.PC]'] != 'NaN']

In [25]:
df = df.rename(columns={"Time Code_x": "Time Code", "Country Name_x": "Country Name"})
del df['Time Code_y']
del df['Country Name_y']

In [26]:
df

,Time,Time Code,Country Name,Country Code,"Percentage of graduates from tertiary education graduating from Agriculture, Forestry, Fisheries and Veterinary programmes, both sexes (%) [SE.TER.GRAD.AG.ZS]",Government expenditure on education as % of GDP (%) [SE.XPD.TOTL.GD.ZS],"Enrolment in tertiary education, all programmes, both sexes (number) [SE.TER.ENRL]","Percentage of graduates from tertiary education graduating from Natural Sciences, Mathematics and Statistics programmes, both sexes (%) [SE.TER.GRAD.SC.ZS]","Enrolment in primary education, both sexes (number) [SE.PRM.ENRL]",CO2 emissions (metric tons per capita) [EN.ATM.CO2E.PC]
0,2020,YR2020,Afghanistan,AFG,NaN,NaN,NaN,NaN,NaN,NaN
1,2020,YR2020,Albania,ALB,NaN,NaN,NaN,NaN,NaN,NaN
2,2020,YR2020,Algeria,DZA,NaN,NaN,NaN,NaN,NaN,NaN
3,2020,YR2020,American Samoa,ASM,NaN,NaN,NaN,NaN,NaN,NaN
4,2020,YR2020,Andorra,AND,NaN,NaN,NaN,NaN,NaN,NaN
5,2020,YR2020,Angola,AGO,NaN,NaN,NaN,NaN,NaN,NaN
6,2020,YR2020,Antigua and Barbuda,ATG,NaN,NaN,NaN,NaN,NaN,NaN
7,2020,YR2020,Arab World,ARB,NaN,NaN,NaN,NaN,NaN,NaN
8,2020,YR2020,Argentina,ARG,NaN,NaN,NaN,NaN,NaN,NaN
9,2020,YR2020,Armenia,ARM,NaN,NaN,NaN,NaN,NaN,NaN
10,2020,YR2020,Aruba,ABW,NaN,NaN,NaN,NaN,NaN,NaN
11,2020,YR2020,Australia,AUS,NaN,NaN,NaN,NaN,NaN,NaN
12,2020,YR2020,Austria,AUT,NaN,NaN,NaN,NaN,NaN,NaN
13,2020,YR2020,Azerbaijan,AZE,NaN,NaN,NaN,NaN,NaN,NaN
14,2020,YR2020,"Bahamas, The",BHS,NaN,NaN,NaN,NaN,NaN,NaN
15,2020,YR2020,Bahrain,BHR,NaN,NaN,NaN,NaN,NaN,NaN
16,2020,YR2020,Bangladesh,BGD,NaN,NaN,NaN,NaN,NaN,NaN
17,2020,YR2020,Barbados,BRB,NaN,NaN,NaN,NaN,NaN,NaN
18,2020,YR2020,Belarus,BLR,NaN,NaN,NaN,NaN,NaN,NaN
19,2020,YR2020,Belgium,BEL,NaN,NaN,NaN,NaN,NaN,NaN
20,2020,YR2020,Belize,BLZ,NaN,NaN,NaN,NaN,NaN,NaN
21,2020,YR2020,Benin,BEN,NaN,NaN,NaN,NaN,NaN,NaN
22,2020,YR2020,Bermuda,BMU,NaN,NaN,NaN,NaN,NaN,NaN
23,2020,YR2020,Bhutan,BTN,NaN,NaN,12248,NaN,94165,NaN
24,2020,YR2020,Bolivia,BOL,NaN,NaN,NaN,NaN,NaN,NaN
25,2020,YR2020,Bosnia and Herzegovina,BIH,NaN,NaN,NaN,NaN,NaN,NaN
26,2020,YR2020,Botswana,BWA,NaN,NaN,NaN,NaN,NaN,NaN
27,2020,YR2020,Brazil,BRA,NaN,NaN,NaN,NaN,NaN,NaN
28,2020,YR2020,British Virgin Islands,VGB,NaN,NaN,NaN,NaN,NaN,NaN
29,2020,YR2020,Brunei Darussalam,BRN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...
13392,1970,YR1970,Turkey,TUR,NaN,NaN,NaN,NaN,NaN,1.222603095
13393,1970,YR1970,Turkmenistan,TKM,NaN,NaN,NaN,NaN,NaN,NaN
13394,1970,YR1970,Turks and Caicos Islands,TCA,NaN,NaN,NaN,NaN,NaN,NaN
13395,1970,YR1970,Tuvalu,TUV,NaN,NaN,NaN,NaN,NaN,NaN
13396,1970,YR1970,Uganda,UGA,NaN,NaN,4232,NaN,729522,0.153610402
13397,1970,YR1970,Ukraine,UKR,NaN,4.57293,NaN,NaN,NaN,NaN
13398,1970,YR1970,United Arab Emirates,ARE,NaN,NaN,NaN,NaN,NaN,65.01695421
13399,1970,YR1970,United Kingdom,GBR,NaN,NaN,NaN,NaN,NaN,11.7323973
13400,1970,YR1970,United States,USA,NaN,NaN,NaN,NaN,NaN,21.11125227
13401,1970,YR1970,Upper middle income,UMC,NaN,NaN,8891124.611,NaN,188462276.9,2.862150253
13402,1970,YR1970,Uruguay,URY,NaN,NaN,NaN,NaN,354096,2.043752689
13403,1970,YR1970,Uzbekistan,UZB,NaN,NaN,NaN,NaN,NaN,NaN
13404,1970,YR1970,Vanuatu,VUT,NaN,NaN,NaN,NaN,18250,0.472457453
13405,1970,YR1970,"Venezuela, RB",VEN,NaN,4.16287,NaN,NaN,NaN,6.542518409
13406,1970,YR1970,Vietnam,VNM,NaN,NaN,NaN,NaN,NaN,0.649680094
13407,1970,YR1970,Virgin Islands (U.S.),VIR,NaN,NaN,NaN,NaN,NaN,NaN
13408,1970,YR1970,West Bank and Gaza,PSE,NaN,NaN,NaN,NaN,NaN,NaN
13409,1970,YR1970,World,WLD,NaN,NaN,31977939.65,NaN,401201714.7,0.00403549
13410,1970,YR1970,"Yemen, Rep.",YEM,NaN,NaN,NaN,NaN,NaN,0.027235837
13411,1970,YR1970,Zambia,ZMB,NaN,4.38781,1433,NaN,694670,0.902037704
13412,1970,YR1970,Zimbabwe,ZWE,NaN,NaN,NaN,NaN,735782,1.543254754
13413,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13414,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13415,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13416,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13417,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13418,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13419,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13420,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13421,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [27]:
df.to_csv('andmed.csv', index=False) #Create a csv from the data

,Time,Time Code_x,Country Name_x,Country Code,"Percentage of graduates from tertiary education graduating from Agriculture, Forestry, Fisheries and Veterinary programmes, both sexes (%) [SE.TER.GRAD.AG.ZS]",Government expenditure on education as % of GDP (%) [SE.XPD.TOTL.GD.ZS],"Enrolment in tertiary education, all programmes, both sexes (number) [SE.TER.ENRL]","Percentage of graduates from tertiary education graduating from Natural Sciences, Mathematics and Statistics programmes, both sexes (%) [SE.TER.GRAD.SC.ZS]","Enrolment in primary education, both sexes (number) [SE.PRM.ENRL]",Time Code_y,Country Name_y,CO2 emissions (metric tons per capita) [EN.ATM.CO2E.PC]
0,2020,YR2020,Afghanistan,AFG,NaN,NaN,NaN,NaN,NaN,YR2020,Afghanistan,NaN
1,2020,YR2020,Albania,ALB,NaN,NaN,NaN,NaN,NaN,YR2020,Albania,NaN
2,2020,YR2020,Algeria,DZA,NaN,NaN,NaN,NaN,NaN,YR2020,Algeria,NaN
3,2020,YR2020,American Samoa,ASM,NaN,NaN,NaN,NaN,NaN,YR2020,American Samoa,NaN
4,2020,YR2020,Andorra,AND,NaN,NaN,NaN,NaN,NaN,YR2020,Andorra,NaN
5,2020,YR2020,Angola,AGO,NaN,NaN,NaN,NaN,NaN,YR2020,Angola,NaN
6,2020,YR2020,Antigua and Barbuda,ATG,NaN,NaN,NaN,NaN,NaN,YR2020,Antigua and Barbuda,NaN
7,2020,YR2020,Arab World,ARB,NaN,NaN,NaN,NaN,NaN,YR2020,Arab World,NaN
8,2020,YR2020,Argentina,ARG,NaN,NaN,NaN,NaN,NaN,YR2020,Argentina,NaN
9,2020,YR2020,Armenia,ARM,NaN,NaN,NaN,NaN,NaN,YR2020,Armenia,NaN
10,2020,YR2020,Aruba,ABW,NaN,NaN,NaN,NaN,NaN,YR2020,Aruba,NaN
11,2020,YR2020,Australia,AUS,NaN,NaN,NaN,NaN,NaN,YR2020,Australia,NaN
12,2020,YR2020,Austria,AUT,NaN,NaN,NaN,NaN,NaN,YR2020,Austria,NaN
13,2020,YR2020,Azerbaijan,AZE,NaN,NaN,NaN,NaN,NaN,YR2020,Azerbaijan,NaN
14,2020,YR2020,"Bahamas, The",BHS,NaN,NaN,NaN,NaN,NaN,YR2020,"Bahamas, The",NaN
15,2020,YR2020,Bahrain,BHR,NaN,NaN,NaN,NaN,NaN,YR2020,Bahrain,NaN
16,2020,YR2020,Bangladesh,BGD,NaN,NaN,NaN,NaN,NaN,YR2020,Bangladesh,NaN
17,2020,YR2020,Barbados,BRB,NaN,NaN,NaN,NaN,NaN,YR2020,Barbados,NaN
18,2020,YR2020,Belarus,BLR,NaN,NaN,NaN,NaN,NaN,YR2020,Belarus,NaN
19,2020,YR2020,Belgium,BEL,NaN,NaN,NaN,NaN,NaN,YR2020,Belgium,NaN
20,2020,YR2020,Belize,BLZ,NaN,NaN,NaN,NaN,NaN,YR2020,Belize,NaN
21,2020,YR2020,Benin,BEN,NaN,NaN,NaN,NaN,NaN,YR2020,Benin,NaN
22,2020,YR2020,Bermuda,BMU,NaN,NaN,NaN,NaN,NaN,YR2020,Bermuda,NaN
23,2020,YR2020,Bhutan,BTN,NaN,NaN,12248,NaN,94165,YR2020,Bhutan,NaN
24,2020,YR2020,Bolivia,BOL,NaN,NaN,NaN,NaN,NaN,YR2020,Bolivia,NaN
25,2020,YR2020,Bosnia and Herzegovina,BIH,NaN,NaN,NaN,NaN,NaN,YR2020,Bosnia and Herzegovina,NaN
26,2020,YR2020,Botswana,BWA,NaN,NaN,NaN,NaN,NaN,YR2020,Botswana,NaN
27,2020,YR2020,Brazil,BRA,NaN,NaN,NaN,NaN,NaN,YR2020,Brazil,NaN
28,2020,YR2020,British Virgin Islands,VGB,NaN,NaN,NaN,NaN,NaN,YR2020,British Virgin Islands,NaN
29,2020,YR2020,Brunei Darussalam,BRN,NaN,NaN,NaN,NaN,NaN,YR2020,Brunei Darussalam,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
13392,1970,YR1970,Turkey,TUR,NaN,NaN,NaN,NaN,NaN,YR1970,Turkey,1.222603095
13393,1970,YR1970,Turkmenistan,TKM,NaN,NaN,NaN,NaN,NaN,YR1970,Turkmenistan,NaN
13394,1970,YR1970,Turks and Caicos Islands,TCA,NaN,NaN,NaN,NaN,NaN,YR1970,Turks and Caicos Islands,NaN
13395,1970,YR1970,Tuvalu,TUV,NaN,NaN,NaN,NaN,NaN,YR1970,Tuvalu,NaN
13396,1970,YR1970,Uganda,UGA,NaN,NaN,4232,NaN,729522,YR1970,Uganda,0.153610402
13397,1970,YR1970,Ukraine,UKR,NaN,4.57293,NaN,NaN,NaN,YR1970,Ukraine,NaN
13398,1970,YR1970,United Arab Emirates,ARE,NaN,NaN,NaN,NaN,NaN,YR1970,United Arab Emirates,65.01695421
13399,1970,YR1970,United Kingdom,GBR,NaN,NaN,NaN,NaN,NaN,YR1970,United Kingdom,11.7323973
13400,1970,YR1970,United States,USA,NaN,NaN,NaN,NaN,NaN,YR1970,United States,21.11125227
13401,1970,YR1970,Upper middle income,UMC,NaN,NaN,8891124.611,NaN,188462276.9,YR1970,Upper middle income,2.862150253
13402,1970,YR1970,Uruguay,URY,NaN,NaN,NaN,NaN,354096,YR1970,Uruguay,2.043752689
13403,1970,YR1970,Uzbekistan,UZB,NaN,NaN,NaN,NaN,NaN,YR1970,Uzbekistan,NaN
13404,1970,YR1970,Vanuatu,VUT,NaN,NaN,NaN,NaN,18250,YR1970,Vanuatu,0.472457453
13405,1970,YR1970,"Venezuela, RB",VEN,NaN,4.16287,NaN,NaN,NaN,YR1970,"Venezuela, RB",6.542518409
13406,1970,YR1970,Vietnam,VNM,NaN,NaN,NaN,NaN,NaN,YR1970,Vietnam,0.649680094
13407,1970,YR1970,Virgin Islands (U.S.),VIR,NaN,NaN,NaN,NaN,NaN,YR1970,Virgin Islands (U.S.),NaN
13408,1970,YR1970,West Bank and Gaza,PSE,NaN,NaN,NaN,NaN,NaN,YR1970,West Bank and Gaza,NaN
13409,1970,YR1970,World,WLD,NaN,NaN,31977939.65,NaN,401201714.7,YR1970,World,0.00403549
13410,1970,YR1970,"Yemen, Rep.",YEM,NaN,NaN,NaN,NaN,NaN,YR1970,"Yemen, Rep.",0.027235837
13411,1970,YR1970,Zambia,ZMB,NaN,4.38781,1433,NaN,694670,YR1970,Zambia,0.902037704
13412,1970,YR1970,Zimbabwe,ZWE,NaN,NaN,NaN,NaN,735782,YR1970,Zimbabwe,1.543254754
13413,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13414,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13415,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13416,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13417,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13418,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13419,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13420,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13421,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN